name: mi-proyecto-env  # Nombre de tu entorno

# Almacenes de paquetes. Al hacer "conda install numpy" conda busca ese paquete en estos canales, empezando por el primero.
# Se pueden añadir más canales o cambiar el orden según las necesidades.
channels:
  - conda-forge   # Un canal comunitario masivo y una organización gestionada por voluntarios. El canal más extenso. Contiene una cantidad enorme de paquetes
  - defaults      # Canal oficial de Anaconda. Contiene paquetes de Anaconda y algunos de los más populares.

dependencies:
  - python=3.11    
  - pip           # Para instalar paquetes desde PyPI: es el repositorio oficial de software de terceros para Python.  Es un índice público y el lugar principal donde los desarrolladores de Python publican sus paquetes y bibliotecas para que otros puedan usarlos

  # Núcleo científico
  - numpy>=1.20
  - scipy>=1.7
  - pandas>=1.3

  # Visualización
  - matplotlib>=3.4
  - seaborn>=0.11

  # Notebooks y utilidades
  - jupyterlab>=3.0   
  - ipykernel         

  # Otras bibliotecas comunes (ejemplos, añade las que necesites)
  # - scikit-learn    # Si haces algo de modelado estadístico/ML ligero
  # - statsmodels
  # - openpyxl        # Para leer/escribir archivos Excel
  # - requests        # Para hacer peticiones HTTP (ej. descargar datos)

  - pip:
    # Aquí puedes listar paquetes que solo están en PyPI o versiones específicas de PyPI
    # - paquete-de-pypi==1.0.0